name: Daily Commit Automation

on:
  schedule:
    # Runs every day at 07:30 UTC (choose a specific hour/minute — not wildcards)
    - cron: '30 7 * * *'
  workflow_dispatch:  # allows manual triggering for testing
  
permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step name includes your email as requested
      - name: Daily Commit Step - 22f3001715@ds.study.iitm.ac.in
        run: |
          echo "Daily update on $(date)" >> daily-log.txt
          git config user.name "GitHub Action Bot"
          git config user.email "22f3001715@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Automated daily update: $(date)"
          git push
